### PR TITLE
DWP Integration Code sample

### PR DESCRIPTION
**Pull request by tavy88**
### Sample calls

1. Looking for jobs that have manager keyword, are in London, on a radius of 2 miles.

```ruby
DwpClient.new.search({q: 'manager', loc: 86384, d: 2}), where loc is the ID for London, d is the distance
```

2. Looking for jobs by postcode area (e.g NW6):

```ruby
irb(main):013:0> DwpClient.new.search({q: 'manager', w: 'NW6'})
title: Manager, url: https://findajob.dwp.gov.uk/apply/2956298, location: Kilburn, North West London, type: permanent
title: Manager, url: https://findajob.dwp.gov.uk/apply/2959734, location: Holloway, North London, type: permanent
title: Product managers, url: https://findajob.dwp.gov.uk/apply/2916024, location: London, UK, type: permanent
title: Community Manager, url: https://findajob.dwp.gov.uk/apply/2900863, location: London, type: permanent
title: Audit Manager / Assistant Manager, url: https://findajob.dwp.gov.uk/apply/2944104, location: London, type: permanent
title: Management Consultant - Senior Manager, url: https://findajob.dwp.gov.uk/apply/2894226, location: London, UK, type: permanent
title: Account manager (Sales) - bilingual; English & Japanese, url: https://findajob.dwp.gov.uk/apply/2929558, location: HA1 1BH, type: permanent
title: Portfolio Manager, url: https://findajob.dwp.gov.uk/apply/2958492, location: Hammersmith, West London, type: permanent
title: Estates Manager, url: https://findajob.dwp.gov.uk/apply/2927834, location: Westminster, South West London, type: contract
title: Maintenance Manager, url: https://findajob.dwp.gov.uk/apply/2848791, location: Westminster, South West London, type: permanent
title: Store Manager, url: https://findajob.dwp.gov.uk/apply/2957747, location: Canary Wharf, London, E14 8JA, type: permanent
title: Line Manager, url: https://findajob.dwp.gov.uk/apply/2969409, location: London, UK, type: contract
title: Deputy Manager, url: https://findajob.dwp.gov.uk/apply/2981122, location: Walthamstow, type: permanent
title: Duty Manager, url: https://findajob.dwp.gov.uk/apply/2869618, location: London, W8 4RT, type: permanent
title: Bid Manager, url: https://findajob.dwp.gov.uk/apply/2979142, location: City of London, London, SW1W 0NT, type: permanent
title: General Manager, url: https://findajob.dwp.gov.uk/apply/2872246, location: Watford, WD19 5RJ, type: permanent
title: Branch Manager, url: https://findajob.dwp.gov.uk/apply/2837391, location: TW9 1TW, type: permanent
```

### Documentation

Screen Shot 2019-09-13 at 10 28 01

### Ticket

https://dfedigital.atlassian.net/browse/GET-238

### CODE REVIEW

**Comment by tavy88** [comment]
@smoothcontract I've attached the bit from the docs that are relevant to the payload. Also, all documentation is attached to the ticket. Hope this makes sense. I am currently experimenting with postcode filtering using it as `w=` as it's documented a bit in the docs but it doesn't look too accurate.

**Comment by smoothcontract** [comment]
> @smoothcontract I've attached the bit from the docs that are relevant to the payload. Also, all documentation is attached to the ticket. Hope this makes sense. I am currently experimenting with postcode filtering using it as `w=` as it's documented a bit in the docs but it doesn't look too accurate.

Okay, have you tried using just the postcode outcode (the first part) alone, rather than the full postcode? We can use the uk_postcode gem to split a postcode into the two sections, and should be accurate enough. Although I guess we don't much control over distance then...

**Comment by tavy88** [comment]
We can use distance within miles with `d` attribute. I have updated the example and hope it makes more sense.

**Comment by tavy88** [comment]
This was just a code sample.

**Pull request closed without merging**
