### PR TITLE
Simplify breadcrumbs on Your Skills page

### PR DESCRIPTION
**Pull request by tavy88**
User can only see the following breadcrumbs items:

Home: Get help to retrain
Your skills

Screen Shot 2019-10-18 at 13 24 41

https://dfedigital.atlassian.net/browse/GET-531

### CODE REVIEW

**Comment by cwrw** [comment]
A good example is this: https://github.com/DFE-Digital/get-help-to-retrain/blob/master/app/controllers/job_profiles_controller.rb#L26

**Comment by smoothcontract** [comment]
> Since this logic has now gone for the skills page, we can cleanup all the params passed around, like search and job profile slug to get to skills

Awesome idea, I like it 👍

**Comment by tavy88** [comment]
I am not sure if it's the right thing to do as it breaks when you remove the last job:

```
  1) Build your skills user sees an error page if they remove their only job selected
     Failure/Error: expect(page).to have_text(/You haven\'t selected any skills/)
       expected to find text matching /You haven\'t selected any skills/ in "Skip to main content\nGOV.UK\nGet help to retrain\nThis service uses cookies to personalise your experience and to collect information about how you use the site. You can find out more about cookies by clicking the cookies settings button.\nAccept cookies Cookie settings\nGOV.UK\nGet help to retrain\nbeta This is a new service – your feedback will help us to improve it.\nHomeGet help to retrain\nGet help to retrain\nHere's what you need to do to retrain for another job.\n1. Check what you are good at\nCheck your existing skills\nYou'll be surprised at what you already know.\n2. Explore the types of jobs you could do\nCan't start yet\nSee types of jobs that match your skills\nYou already have many of the skills to do these types of jobs. Find out what additional training you might need.\n3. Find training that's right for you\nCan't start yet\nFind a training course\nTraining can help you access a broader range of jobs and stay in secure work.\n4. Get help changing jobs\nCan't start yet\nFurther help to find work\nGet help writing a CV and cover letter and preparing for interview. See if on-the-job training is right for you and find local support.\n5. Help improve this service\nCan't start yet\nTake a quick survey\nTell us about your experience using Get help to retrain.\nFree local advice\nGet advice on changing jobs and finding training in your area.\nCall free on\n0800 051 0459\nMonday to Friday, 9am to 5pm\nReturn to saved results\nIf you've already used this service before and saved your results, enter your email address. We'll send you a link you can use to return to your saved results.\nEmail\nSend a link\nIs this page useful?\nYes No\nThank you for your feedback\nSupport links\nCookies Privacy\nAll content is available under the Open Government Licence v3.0, except where otherwise stated\n© Crown copyright"
     # ./spec/features/skills_builder_spec.rb:384:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:49:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:48:in `block (2 levels) in <top (required)>'

  2) Build your skills user can remove job and they can see it again in search results
     Failure/Error: click_on('Check my skills')

     Capybara::ElementNotFound:
       Unable to find link or button "Check my skills"
     # ./spec/features/skills_builder_spec.rb:392:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:49:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:48:in `block (2 levels) in <top (required)>'```

You get redirected to task list and you shouldn't.

**Comment by cwrw** [comment]
ah it seems we need the profile id for showing the skills page when removing. Its ok we can revisit this later, ✅

**Pull request merged**
